1 module
js-tasks-ru/jsbasic-20211108_stas-sokolovskyy pull request #2
Opened 2021-11-15 15:08 UTC by 4stazy

2021-11-15 15:09 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-15 15:51 UTC, SinimaWath requested changes

2021-11-15 15:51 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  var result = 1;
Давай не использовать в коде var, на лекции как раз рассказывал, про современные альтернативы

2021-11-15 15:51 UTC, SinimaWath commented on 1-module/2-task/index.js
> +    return ((name.indexOf(' ') < 0) && (name.length >= 4));
indexOf - лучше не использовать, у него не самое очевидное поведение. 

Давай использовать более подходящий includes, который возвращает boolean

2021-11-15 15:51 UTC, SinimaWath commented on 1-module/5-task/task.test.js
> -});
Тесты не нужно изменять ( Верни как было плиз

2021-11-15 15:51 UTC, SinimaWath commented on 1-module/4-task/task.test.js
> -});
Тесты не нужно изменять ( Верни как было плиз

2021-11-16 16:05 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-11-17 16:44 UTC, SinimaWath approved these changes

2021-11-17 16:45 UTC, merged